#! /usr/bin/env slsh
% -*- mode: SLANG; mode: fold; -*- %

require("xfig.sl");

% define colors
private define prepare (gray) {
  if (gray) {
    xfig_new_color("pse_base", 0x000000);
    xfig_new_color("pse_border", 0x000000);
    xfig_new_color("pse_background", 0xffffff);
    xfig_new_color("pse_info", 0x000000);
    xfig_new_color("pse_hydrogen", 0xffffff);
    xfig_new_color("pse_noble_gas", 0xffffff);
    xfig_new_color("pse_alkali_metal", 0xffffff);
    xfig_new_color("pse_alkaline_earth_metal", 0xffffff);
    xfig_new_color("pse_transition_metal", 0xffffff);
    xfig_new_color("pse_post_transition_metal", 0xffffff);
    xfig_new_color("pse_metalloid", 0xffffff);
    xfig_new_color("pse_nonmetal", 0xffffff);
    xfig_new_color("pse_halogen", 0xffffff);
    xfig_new_color("pse_lanthanide", 0xffffff);
    xfig_new_color("pse_actinide", 0xffffff);
    xfig_new_color("pse_transactinide", 0xffffff);
    xfig_new_color("pse_unknown", 0xffffff);
  } else {
    xfig_new_color("pse_base", 0x2a2a2a);
    xfig_new_color("pse_border", 0x2a2a2a);
    xfig_new_color("pse_background", 0x2a2a2a);
    xfig_new_color("pse_info", 0xf3f2f2);
    xfig_new_color("pse_hydrogen", 0x7ab1fc);
    xfig_new_color("pse_noble_gas", 0x30d6c7);
    xfig_new_color("pse_alkali_metal", 0xd6b933);
    xfig_new_color("pse_alkaline_earth_metal", 0xc88b2e);
    xfig_new_color("pse_transition_metal", 0x1d47cb);
    xfig_new_color("pse_post_transition_metal", 0x523deb);
    xfig_new_color("pse_metalloid", 0xad1953);
    xfig_new_color("pse_nonmetal", 0xca2c38);
    xfig_new_color("pse_halogen", 0x5db961);
    xfig_new_color("pse_lanthanide", 0xb746c8);
    xfig_new_color("pse_actinide", 0x9146c8);
    xfig_new_color("pse_transactinide", 0xf2da12);
    xfig_new_color("pse_unknown", 0x6d6d6d);
  }
  
  % redefine png & pdf driver
  variable png = "fig2dev -L png %F %I %O";
  png = strreplace(png, "%F", sprintf("-g \\#%x", xfig_lookup_color_rgb("pse_background")));
  xfig_set_output_driver("png", png);
  variable pdf = "fig2dev -L pdf %F %I %O";
  pdf = strreplace(pdf, "%F", sprintf("-g \\#%x", xfig_lookup_color_rgb("pse_background")));
  xfig_set_output_driver("pdf", pdf);
  % change paper size & font
  xfig_set_paper_size("A4");
  xfig_set_font_style("\sffamily\bfseries"R);
}

private variable ecols = ["pse_hydrogen", "pse_alkali_metal", "pse_alkaline_earth_metal", "pse_transition_metal",
			  "pse_post_transition_metal", "pse_metalloid", "pse_halogen", "pse_transactinide",
			  "pse_nonmetal", "pse_noble_gas", "pse_lanthanide", "pse_actinide", "pse_unknown"];

% phases
private variable SOLID, LIQUID, GAS, SYNTETIC;
(SOLID, LIQUID, GAS, SYNTETIC) = (0,1,2, 3);
private variable STABLE, UNSTABLE;
(STABLE, UNSTABLE) = (0, 1);
% classification
private variable HYDROGEN, ALKALI_METAL, ALKALINE_EARTH_METAL, TRANSITION_METAL, POST_TRANSITION_METAL, METALLOID, HALOGEN, TRANSACTINIDE, NONMETAL, NOBLE_GAS, LANTHANIDE, ACTINIDE, UNKNOWN;
(HYDROGEN, ALKALI_METAL, ALKALINE_EARTH_METAL, TRANSITION_METAL, POST_TRANSITION_METAL, METALLOID, HALOGEN, TRANSACTINIDE, NONMETAL, NOBLE_GAS, LANTHANIDE, ACTINIDE, UNKNOWN) = (0,1,2,3,4,5,6,7,8,9,10,11,12);
% reduction type
private variable _P2N, _N2N, _EOH;
(_P2N, _N2N, _EOH) = (0,1,2);

variable element = { %{{{
  struct { %{{{
    name = "Hydrogen",
    number = 1,
    symbol = "H",
    oxidation_stages = [1,-1],
    electron_configuration = "1s",
    atomic_radius = {37.3, 30, 100, "210^{-}_{1}"},
    reduction_potential = {0, 1, _P2N},
    electronegativity = 2.2,
    mass_fraction = 0.88,
    classification = HYDROGEN,
    state = GAS,
    radio_active = STABLE,
    isotope = {3, "\beta^{-}", "12.3\,a"},
    atomic_mass = 1.008,
    number_natural_isotopes = 2,
    mass_number = [1,2],
    abundances = [0.99985, 0.00015],
    ionisation_energy = 13.598,
    density = 0.084,
    transition_point = [14.01, 20.28],
  }, %}}}
  struct { %{{{
    name = "Helium",
    number = 2,
    symbol = "He",
    oxidation_stages = NULL,
    electron_configuration = "1s^{2}",
    atomic_radius = {NULL, 140, NULL},
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = 4e-7,
    classification = NOBLE_GAS,
    state = GAS,
    radio_active = STABLE,
    isotope = {6, "\beta^{-}", "808\,ms"},
    atomic_mass = 4.003,
    number_natural_isotopes = 2,
    mass_number = [3,4],
    abundances = [1e-6, 1],
    ionisation_energy = 24.587,
    density = -0.47,
    transition_point = [0.95, 4.22],
  }, %}}}
  struct { %{{{
    name = "Lithium",
    number = 3,
    symbol = "Li",
    oxidation_stages = 1,
    electron_configuration = "2s",
    atomic_radius = {152, 123, NULL, "59^{+}_{4}", "76^{+}_{6}"},
    reduction_potential = {-3.04, 1, _P2N},
    electronegativity = 1.0,
    mass_fraction = 6e-3,
    classification = ALKALI_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {8, "\beta^{-}", "842\,ms"},
    atomic_mass = 6.94,
    number_natural_isotopes = 2,
    mass_number = [6,7],
    abundances = [0.075, 0.925],
    ionisation_energy = 5.392,
    density = 0.53,
    transition_point = [453.69, 1615.],
  }, %}}}
  struct { %{{{
    name = "Beryllium",
    number = 4,
    symbol = "Be",
    oxidation_stages = 2,
    electron_configuration = "2s^{2}",
    atomic_radius = {111.3, 89, NULL, "27^{2+}_{4}", "45^{2+}_{6}"},
    reduction_potential = {-1.85, 2, _P2N},
    electronegativity = 1.5,
    mass_fraction = 5e-4,
    classification = ALKALINE_EARTH_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {7, "\epsilon \gamma", "53\,d"},
    atomic_mass = 9.012,
    number_natural_isotopes = 1,
    mass_number = 9,
    abundances = 1.0,
    ionisation_energy = 9.322,
    density = 1.85,
    transition_point = [1560., 2742.],
  }, %}}}
  struct { %{{{
    name = "Boron",
    number = 5,
    symbol = "B",
    oxidation_stages = 3,
    electron_configuration = "2s^{2}2p",
    atomic_radius = {79.5, 81, NULL, "1^{3+}_{1}", "11^{3+}_{4}"},
    reduction_potential = NULL,
    electronegativity = 2.0,
    mass_fraction = 1e-3,
    classification = METALLOID,
    state = SOLID,
    radio_active = STABLE,
    isotope = {12, "\beta^{-} \gamma", "20\,ms"},
    atomic_mass = 10.81,
    number_natural_isotopes = 2,
    mass_number = [10, 11],
    abundances = [0.199, 0.801],
    ionisation_energy = 8.298,
    density = 2.35,
    transition_point = [2349., 4200.],
  }, %}}}
  struct { %{{{
    name = "Carbon",
    number = 6,
    symbol = "C",
    oxidation_stages = [4,2,-4],
    electron_configuration = "2s^{2}2p^{2}",
    atomic_radius = {77.2, 77, 170, "15^{4+}_{4}"},
    reduction_potential = NULL,
    electronegativity = 2.5,
    mass_fraction = 0.09,
    classification = NONMETAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {14, "\beta^{-}", "5730\,a"},
    atomic_mass = 12.011,
    number_natural_isotopes = 2,
    mass_number = [12, 13],
    abundances = [0.9889, 0.0111],
    ionisation_energy = 11.260,
    density = 3.51,
    transition_point = [3823., 4098.],
  }, %}}}
  struct { %{{{
    name = "Nitrogen",
    number = 7,
    symbol = "N",
    oxidation_stages = [5,4,3,2,-3],
    electron_configuration = "2s^{2}2p^{2}",
    atomic_radius = {54.9, 70, 150, "146^{3-}_{4}"},
    reduction_potential = NULL,
    electronegativity = 3.1,
    mass_fraction = 0.03,
    classification = NONMETAL,
    state = GAS,
    radio_active = STABLE,
    isotope = {13, "\beta^{+}", "10\,m"},
    atomic_mass = 14.007,
    number_natural_isotopes = 2,
    mass_number = [14, 15],
    abundances = [0.9964, 0.0036],
    ionisation_energy = 14.534,
    density = -1.25,
    transition_point = [63.15, 77.36],
  }, %}}}
  struct { %{{{
    name = "Oxygen",
    number = 8,
    symbol = "O",
    oxidation_stages = [-2, -1],
    electron_configuration = "2s^{2}2p^{4}",
    atomic_radius = {60.4, 66, 140, "138^{2-}_{4}"},
    reduction_potential = NULL,
    electronegativity = 3.5,
    mass_fraction = 49.4,
    classification = NONMETAL,
    state = GAS,
    radio_active = STABLE,
    isotope = {15, "\beta^{+}", "2\,m"},
    atomic_mass = 15.999,
    number_natural_isotopes = 3,
    mass_number = [16, 17, 18],
    abundances = [0.9976, 0.0004, 0.002],
    ionisation_energy = 13.618,
    density = -1.43,
    transition_point = [54.36, 90.20],
  }, %}}}
  struct { %{{{
    name = "Fluorine",
    number = 9,
    symbol = "F",
    oxidation_stages = -1,
    electron_configuration = "2s^{2}2p^{5}",
    atomic_radius = {70.9, 64, 140, "133^{-}_{6}"},
    reduction_potential = {2.87, 1, _N2N},
    electronegativity = 4.1,
    mass_fraction = 0.03,
    classification = HALOGEN,
    state = GAS,
    radio_active = STABLE,
    isotope = {18, "\beta^{+}", "110\,m"},
    atomic_mass = 18.998,
    number_natural_isotopes = 1,
    mass_number = 19,
    abundances = 1.0,
    ionisation_energy = 17.422,
    density = -1.70,
    transition_point = [53.53, 85.03],
  }, %}}}
  struct { %{{{
    name = "Neon",
    number = 10,
    symbol = "Ne",
    oxidation_stages = NULL,
    electron_configuration = "2s^{2}2p^{6}",
    atomic_radius = {NULL, NULL, 150},
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = 5e-7,
    classification = NOBLE_GAS,
    state = GAS,
    radio_active = STABLE,
    isotope = {23, "\beta^{-} \gamma", "37\,s"},
    atomic_mass = 20.180,
    number_natural_isotopes = 3,
    mass_number = [20, 21, 22],
    abundances = [0.905, 0.003, 0.092],
    ionisation_energy = 21.564,
    density = -0.90,
    transition_point = [24.56, 27.02],
  }, %}}}
  struct { %{{{
    name = "Sodium",
    number = 11,
    symbol = "Na",
    oxidation_stages = 1,
    electron_configuration = "3s",
    atomic_radius = {185.8, 157, NULL, "99^{+}_{4}", "102^{+}_{6}"},
    reduction_potential = {-2.71, 1, _P2N},
    electronegativity = 1.0,
    mass_fraction = 2.64,
    classification = ALKALI_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {22, "\beta^{+} \gamma", "2.6\,a"},
    atomic_mass = 22.990,
    number_natural_isotopes = 1,
    mass_number = 23,
    abundances = 1.0,
    ionisation_energy = 5.139,
    density = 0.97,
    transition_point = [370.87, 1156.],
  }, %}}}
  struct { %{{{
    name = "Magnesium",
    number = 12,
    symbol = "Mg",
    oxidation_stages = 2,
    electron_configuration = "3s^{2}",
    atomic_radius = {159.9, 136, NULL, "57^{2+}_{4}", "72^{2+}_{6}"},
    reduction_potential = {-2.372, 2, _P2N},
    electronegativity = 1.2,
    mass_fraction = 1.94,
    classification = ALKALINE_EARTH_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {28, "\beta^{-} \gamma", "21\,h"},
    atomic_mass = 24.305,
    number_natural_isotopes = 3,
    mass_number = [24,25,26],
    abundances = [0.79, 0.1, 0.11],
    ionisation_energy = 7.646,
    density = 1.74,
    transition_point = [923., 1363.],
  }, %}}}
  struct { %{{{
    name = "Aluminium",
    number = 13,
    symbol = "Al",
    oxidation_stages = 3,
    electron_configuration = "3s^{2}3p",
    atomic_radius = {143.2, 125, NULL, "39^{3+}_{4}", "54^{3-}_{6}"},
    reduction_potential = {-1.662, 3, _P2N},
    electronegativity = 1.5,
    mass_fraction = 7.57,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {26, "\beta^{+} \gamma", "7.2\cdot10^{5}\,a"},
    atomic_mass = 26.982,
    number_natural_isotopes = 1,
    mass_number = 27,
    abundances = 1.0,
    ionisation_energy = 5.986,
    density = 2.70,
    transition_point = [933.47, 2792.],
  }, %}}}
  struct { %{{{
    name = "Silicon",
    number = 14,
    symbol = "Si",
    oxidation_stages = [4, -4],
    electron_configuration = "3s^{2}3p^{2}",
    atomic_radius = {117.6, 117, NULL, "26^{4+}_{4}", "40^{4+}_{6}"},
    reduction_potential = NULL,
    electronegativity = 1.7,
    mass_fraction = 25.8,
    classification = METALLOID,
    state = SOLID,
    radio_active = STABLE,
    isotope = {31, "\beta^{-}", "3\,"},
    atomic_mass = 28.085,
    number_natural_isotopes = 3,
    mass_number = [28,29,30],
    abundances = [0.922, 0.047, 0.031],
    ionisation_energy = 8.151,
    density = 2.33,
    transition_point = [1687., 3538.],
  }, %}}}
  struct { %{{{
    name = "Phosphorus",
    number = 15,
    symbol = "P",
    oxidation_stages = [5,3,-3],
    electron_configuration = "3s^{2}3p^{3}",
    atomic_radius = {110.5, 110, NULL, "17^{5+}_{4}", "44^{3+}_{6}"},
    reduction_potential = NULL,
    electronegativity = 2.1,
    mass_fraction = 0.09,
    classification = NONMETAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {32, "\beta^{-}", "14\,d"},
    atomic_mass = 30.974,
    number_natural_isotopes = 1,
    mass_number = 31,
    abundances = 1.0,
    ionisation_energy = 10.486,
    density = 1.82,
    transition_point = [317.30, 553.65],
  }, %}}}
  struct { %{{{
    name = "Sulfur",
    number = 16,
    symbol = "S",
    oxidation_stages = [6,4,2,-2],
    electron_configuration = "3s^{2}3p^{4}",
    atomic_radius = {103.5, 104, 180, "184^{2+}_{6}"},
    reduction_potential = {-0.48, 2, _N2N},
    electronegativity = 2.4,
    mass_fraction = 0.05,
    classification = NONMETAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {35, "\beta^{-}", "88\,d"},
    atomic_mass = 32.06,
    number_natural_isotopes = 4,
    mass_number = [32,33,34],
    abundances = [0.95, 0.007, 0.043],
    ionisation_energy = 10.36,
    density = 2.07,
    transition_point = [388.36, 717.8],
  }, %}}}
  struct { %{{{
    name = "Chlorine",
    number = 17,
    symbol = "Cl",
    oxidation_stages = [7,5,3,1,-1],
    electron_configuration = "3s^{2}3p^{5}",
    atomic_radius = {99.4, 99, 180, "181^{-}_{6}"},
    reduction_potential = {1.358, 1, _N2N},
    electronegativity = 2.8,
    mass_fraction = 0.19,
    classification = HALOGEN,
    state = GAS,
    radio_active = STABLE,
    isotope = {36, "\beta^{-}", "3\cdot10^{5}\,5"},
    atomic_mass = 35.45,
    number_natural_isotopes = 2,
    mass_number = [35,37],
    abundances = [0.758, 0.242],
    ionisation_energy = 12.967,
    density = -3.2,
    transition_point = [171.6, 239.11],
  }, %}}}
  struct { %{{{
    name = "Argon",
    number = 18,
    symbol = "Ar",
    oxidation_stages = NULL,
    electron_configuration = "3s^{2}3p^{6}",
    atomic_radius = {NULL, NULL, 180},
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = 4e-4,
    classification = NOBLE_GAS,
    state = GAS,
    radio_active = STABLE,
    isotope = {41, "\beta^{-} \gamma", "2\,h"},
    atomic_mass = 39.948,
    number_natural_isotopes = 3,
    mass_number = [36,38,40],
    abundances = [0.003, 0.001, 0.996],
    ionisation_energy = 15.759,
    density = -1.784,
    transition_point = [83.8, 87.3],
  }, %}}}
  struct { %{{{
    name = "Potassium",
    number = 19,
    symbol = "K",
    oxidation_stages = 1,
    electron_configuration = "4s",
    atomic_radius = {227.2, 203, NULL, "138^{+}_{6}", "151^{+}_{8}"},
    reduction_potential = {-2.93, 1, _P2N},
    electronegativity = 0.9,
    mass_fraction = 2.4,
    classification = ALKALI_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {42, "\beta^{-} \gamma", "12\,h"},
    atomic_mass = 39.098,
    number_natural_isotopes = 3,
    mass_number = [39,-40,41],
    abundances = [0.933, 0.0001, 0.067],
    ionisation_energy = 4.341,
    density = 0.86,
    transition_point = [336.53, 1032.],
  }, %}}}
  struct { %{{{
    name = "Calcium",
    number = 20,
    symbol = "Ca",
    oxidation_stages = 2,
    electron_configuration = "4s^{2}",
    atomic_radius = {197.4, 174, NULL, "100^{2+}_{6}", "112^{2+}_{8}"},
    reduction_potential = {-2.87, 2, _P2N},
    electronegativity = 1.0,
    mass_fraction = 3.39,
    classification = ALKALINE_EARTH_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {45, "\beta^{-}", "163\,d"},
    atomic_mass = 40.078,
    number_natural_isotopes = 6,
    mass_number = [40,42,44],
    abundances = [0.969, 0.006, 0.021],
    ionisation_energy = 6.113,
    density = 1.54,
    transition_point = [1115., 1757.],
  }, %}}}
  struct { %{{{
    name = "Scandium",
    number = 21,
    symbol = "Sc",
    oxidation_stages = 3,
    electron_configuration = "3d4s^{2}",
    atomic_radius = {160.6, 144, NULL, "75^{3+}_{6}", "87^{3+}_{8}"},
    reduction_potential = {-2.077, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = 5e-4,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {46, "\beta^{-} \gamma", "84\,d"},
    atomic_mass = 44.956,
    number_natural_isotopes = 1,
    mass_number = 45,
    abundances = 1.0,
    ionisation_energy = 6.54,
    density = 2.99,
    transition_point = [1814., 3109.],
  }, %}}}
  struct { %{{{
    name = "Titanium",
    number = 22,
    symbol = "Ti",
    oxidation_stages = [4,3],
    electron_configuration = "3d^{2}4s^{2}",
    atomic_radius = {144.8, 132, NULL, "42^{4+}_{6}", "61^{4+}_{6}"},
    reduction_potential = {-1.63, 2, _P2N},
    electronegativity = 1.3,
    mass_fraction = 0.41,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {44, "\epsilon \gamma", "47.3\,a"},
    atomic_mass = 47.867,
    number_natural_isotopes = 5,
    mass_number = [46,47,48],
    abundances = [0.083, 0.074, 0.737],
    ionisation_energy = 6.82,
    density = 4.51,
    transition_point = [1941., 3560.],
  }, %}}}
  struct { %{{{
    name = "Vanadium",
    number = 23,
    symbol = "V",
    oxidation_stages = [5,4,3,2,0],
    electron_configuration = "3d^{3}4s^{2}",
    atomic_radius = {131.1, 122, NULL, "54^{5+}_{6}", "79^{2+}_{6}"},
    reduction_potential = {-1.175, 2, _P2N},
    electronegativity = 1.5,
    mass_fraction = 0.01,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {49, "\epsilon", "330\,d"},
    atomic_mass = 50.942,
    number_natural_isotopes = 2,
    mass_number = [50,51],
    abundances = [0.002, 0.998],
    ionisation_energy = 6.74,
    density = 6.09,
    transition_point = [2183., 3680.],
  }, %}}}
  struct { %{{{
    name = "Chromium",
    number = 24,
    symbol = "Cr",
    oxidation_stages = [6,3,2,0],
    electron_configuration = "3d^{5}4s",
    atomic_radius = {124.9, 118, NULL, "26^{6+}_{6}", "61^{3+}_{6}"},
    reduction_potential = {-0.744, 3, _P2N},
    electronegativity = 1.6,
    mass_fraction = 0.02,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {51, "\epsilon \gamma", "28\,d"},
    atomic_mass = 51.996,
    number_natural_isotopes = 4,
    mass_number = [50,52,53],
    abundances = [0.043, 0.838, 0.096],
    ionisation_energy = 6.766,
    density = 7.14,
    transition_point = [2180., 2944.],
  }, %}}}
  struct { %{{{
    name = "Manganese",
    number = 25,
    symbol = "Mn",
    oxidation_stages = [7,6,4,3,2,0,-1],
    electron_configuration = "3d^{5}4s^{2}",
    atomic_radius = {136.7, 118, "25^{7+}_{4}", "83^{2+}_{6}"},
    reduction_potential = {-1.185, 2, _P2N},
    electronegativity = 1.6,
    mass_fraction = 0.09,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {54, "\epsilon \gamma", "312\,d"},
    atomic_mass = 54.938,
    number_natural_isotopes = 1,
    mass_number = 55,
    abundances = 1.0,
    ionisation_energy = 7.435,
    density = 7.44,
    transition_point = [1519., 2334.],
  }, %}}}
  struct { %{{{
    name = "Iron",
    number = 26,
    symbol = "Fe",
    oxidation_stages = [6,3,2,0,-2],
    electron_configuration = "3d^{6}4s^{2}",
    atomic_radius = {124.1, 116, NULL, "65^{3+}_{6}", "78^{2+}_{6}"},
    reduction_potential = {-0.447, 2, _P2N},
    electronegativity = 1.6,
    mass_fraction = 4.7,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {59, "\beta^{-} \gamma", "45\,d"},
    atomic_mass = 55.845,
    number_natural_isotopes = 4,
    mass_number = [54,56,57],
    abundances = [0.058, 0.918, 0.021],
    ionisation_energy = 7.87,
    density = 7.87,
    transition_point = [1811., 3134.],
  }, %}}}
  struct { %{{{
    name = "Cobalt",
    number = 27,
    symbol = "Co",
    oxidation_stages = [3,2,0,-1],
    electron_configuration = "3d^{7}4s^{2}",
    atomic_radius = {125.3, 116, NULL, "61^{3+}_{6}", "75^{2+}_{6}"},
    reduction_potential = {-0.28, 2, _P2N},
    electronegativity = 1.7,
    mass_fraction = 4e-3,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {60, "\beta^{-} \gamma", "5.3\,a"},
    atomic_mass = 58.933,
    number_natural_isotopes = 1,
    mass_number = 59,
    abundances = 1.0,
    ionisation_energy = 7.86,
    density = 8.89,
    transition_point = [1768., 3200.],
  }, %}}}
  struct { %{{{
    name = "Nickel",
    number = 28,
    symbol = "Ni",
    oxidation_stages = [3,2,0],
    electron_configuration = "3d^{8}4s^{2}",
    atomic_radius = {124.6, 115, NULL, "55^{2+}_{tetr}", "69^{2+}_{6}"},
    reduction_potential = {-0.257, 2, _P2N},
    electronegativity = 1.8,
    mass_fraction = 0.01,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {63, "\beta^{-}", "100\,a"},
    atomic_mass = 58.693,
    number_natural_isotopes = 5,
    mass_number = [58,60,62],
    abundances = [0.681, 0.262, 0.036],
    ionisation_energy = 7.635,
    density = 8.91,
    transition_point = [1728., 3186.],
  }, %}}}
  struct { %{{{
    name = "Copper",
    number = 29,
    symbol = "Cu",
    oxidation_stages = [2,1],
    electron_configuration = "3d^{10}4s",
    atomic_radius = {127.8, 117, NULL, "57^{2+}_{4}", "46^{+}_{2}"},
    reduction_potential = {0.342, 2, _P2N},
    electronegativity = 1.8,
    mass_fraction = 0.01,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {64, "\beta^{-} \epsilon", "13\,h"},
    atomic_mass = 63.546,
    number_natural_isotopes = 2,
    mass_number = [63,65],
    abundances = [0.692, 0.308],
    ionisation_energy = 7.726,
    density = 8.92,
    transition_point = [1357.77, 2835.],
  }, %}}}
  struct { %{{{
    name = "Zinc",
    number = 30,
    symbol = "Zn",
    oxidation_stages = 2,
    electron_configuration = "3d^{10}4s^{2}",
    atomic_radius = {133.5, 125, NULL, "60^{2+}_{4}", "73^{2+}_{6}"},
    reduction_potential = {-0.762, 2, _P2N},
    electronegativity = 1.7,
    mass_fraction = 0.01,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {65, "\epsilon \gamma", "244\,d"},
    atomic_mass = 65.38,
    number_natural_isotopes = 5,
    mass_number = [64,66,68],
    abundances = [0.486,0.279,0.188],
    ionisation_energy = 9.394,
    density = 7.14,
    transition_point = [692.68, 1180.],
  }, %}}}
  struct { %{{{
    name = "Gallium",
    number = 31,
    symbol = "Ga",
    oxidation_stages = 3,
    electron_configuration = "3d^{10}4s^{2}4p",
    atomic_radius = {122.1, 125, NULL, "47^{3+}_{4}", "62^{3+}_{6}"},
    reduction_potential = {-0.56, 3, _P2N},
    electronegativity = 1.8,
    mass_fraction = 1e-3,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {67, "\epsilon \gamma", "78\,h"},
    atomic_mass = 69.723,
    number_natural_isotopes = 2,
    mass_number = [69,71],
    abundances = [0.601, 0.399],
    ionisation_energy = 5.999,
    density = 5.91,
    transition_point = [302.9146, 2477.],
  }, %}}}
  struct { %{{{
    name = "Germanium",
    number = 32,
    symbol = "Ge",
    oxidation_stages = 4,
    electron_configuration = "3d^{10}4s^{2}4p^{2}",
    atomic_radius = {122.5, 122, NULL, "39^{4+}_{4}", "53^{4+}_{6}"},
    reduction_potential = {0.24, 2, _P2N},
    electronegativity = 2.0,
    mass_fraction = 6e-4,
    classification = METALLOID,
    state = SOLID,
    radio_active = STABLE,
    isotope = {77, "\beta^{-} \gamma", "11\,h"},
    atomic_mass = 72.63,
    number_natural_isotopes = 5,
    mass_number = [70,72,74],
    abundances = [0.204, 0.273, 0.367],
    ionisation_energy = 7.899,
    density = 5.32,
    transition_point = [302.9146, 3106.],
  }, %}}}
  struct { %{{{
    name = "Arsenic",
    number = 33,
    symbol = "As",
    oxidation_stages = [5,3,-3],
    electron_configuration = "3d^{10}4s^{2}4p^{3}",
    atomic_radius = {124.5, 121, NULL, "34^{5+}_{4}", "58^{3+}_{6}"},
    reduction_potential = {0.234, 3, _EOH},
    electronegativity = 2.2,
    mass_fraction = 6e-4,
    classification = METALLOID,
    state = SOLID,
    radio_active = STABLE,
    isotope = {73, "\epsilon \gamma", "80\,d"},
    atomic_mass = 74.922,
    number_natural_isotopes = 1,
    mass_number = 75,
    abundances = 1.0,
    ionisation_energy = 9.81,
    density = 5.72,
    transition_point = [1090., 887.],
  }, %}}}
  struct { %{{{
    name = "Selenium",
    number = 34,
    symbol = "Se",
    oxidation_stages = [6,4,-2],
    electron_configuration = "3d^{10}4s^{2}4p^{4}",
    atomic_radius = {116, 117, NULL, "50^{4+}_{6}", "198^{2-}_{6}"},
    reduction_potential = {-0.924, 2, _N2N},
    electronegativity = 2.5,
    mass_fraction = 8e-5,
    classification = NONMETAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {75, "\epsilon \gamma", "120\,d"},
    atomic_mass = 78.96,
    number_natural_isotopes = 6,
    mass_number = [76,78,80],
    abundances = [0.094, 0.238, 0.496],
    ionisation_energy = 9.752,
    density = 4.19,
    transition_point = [494., 958.],
  }, %}}}
  struct { %{{{
    name = "Bromine",
    number = 35,
    symbol = "Br",
    oxidation_stages = [7,5,3,1,-1],
    electron_configuration = "3d^{10}4s^{2}4p^{5}",
    atomic_radius = {114.5, 114, 200, "196^{-}_{6}"},
    reduction_potential = {1.066, 1, _N2N},
    electronegativity = 2.7,
    mass_fraction = 6e-4,
    classification = HALOGEN,
    state = LIQUID,
    radio_active = STABLE,
    isotope = {82, "\beta^{-} \gamma", "35\,h"},
    atomic_mass = 79.904,
    number_natural_isotopes = 2,
    mass_number = [79,81],
    abundances = [0.507, 0.493],
    ionisation_energy = 11.814,
    density = 3.14,
    transition_point = [265.8, 332.],
  }, %}}}
  struct { %{{{
    name = "Krypton",
    number = 36,
    symbol = "Kr",
    oxidation_stages = 2,
    electron_configuration = "3d^{10}4s^{2}4p^{6}",
    atomic_radius = {NULL, NULL, 190},
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = 2e-8,
    classification = NOBLE_GAS,
    state = GAS,
    radio_active = STABLE,
    isotope = {85, "\beta^{-}", "10.8\,a"},
    atomic_mass = 83.798,
    number_natural_isotopes = 6,
    mass_number = [82,84,86],
    abundances = [0.116, 0.57, 0.173],
    ionisation_energy = 13.999,
    density = -3.75,
    transition_point = [115.79, 119.93],
  }, %}}}
  struct { %{{{
    name = "Rubidium",
    number = 37,
    symbol = "Rb",
    oxidation_stages = 1,
    electron_configuration = "5s",
    atomic_radius = {247.5, 216, NULL, "152^{+}_{6}", "161^{+}_{8}"},
    reduction_potential = {-2.98, 1, _P2N},
    electronegativity = 0.9,
    mass_fraction = 0.03,
    classification = ALKALI_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {86, "\beta^{-} \gamma", "19\,d"},
    atomic_mass = 85.468,
    number_natural_isotopes = 2,
    mass_number = [85,-87],
    abundances = [0.722, 0.278],
    ionisation_energy = 4.177,
    density = 1.53,
    transition_point = [312.46, 961.],
  }, %}}}
  struct { %{{{
    name = "Strontium",
    number = 38,
    symbol = "Sr",
    oxidation_stages = 2,
    electron_configuration = "5s^{2}",
    atomic_radius = {215.1, 191, NULL, "118^{2+}_{6}", "126^{2+}_{8}"},
    reduction_potential = {-2.89, 2, _P2N},
    electronegativity = 1.0,
    mass_fraction = 0.01,
    classification = ALKALINE_EARTH_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {90, "\beta^{-}", "28.5\,a"},
    atomic_mass = 87.62,
    number_natural_isotopes = 4,
    mass_number = [86,87,88],
    abundances = [0.099, 0.07, 0.826],
    ionisation_energy = 5.695,
    density = 2.63,
    transition_point = [1050., 1655.],
  }, %}}}
  struct { %{{{
    name = "Yttrium",
    number = 39,
    symbol = "Y",
    oxidation_stages = 3,
    electron_configuration = "4d5s^{2}",
    atomic_radius = {177.6, 162, NULL, "90^{3+}_{6}"},
    reduction_potential = {-2.372, 2, _P2N},
    electronegativity = 1.1,
    mass_fraction = 3e-3,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {88, "\epsilon \gamma", "107\,d"},
    atomic_mass = 88.906,
    number_natural_isotopes = 1,
    mass_number = 89,
    abundances = 1.0,
    ionisation_energy = 6.38,
    density = 4.47,
    transition_point = [1799., 3609.],
  }, %}}}
  struct { %{{{
    name = "Zirconium",
    number = 40,
    symbol = "Zr",
    oxidation_stages = 4,
    electron_configuration = "4d^{2}5s^{2}",
    atomic_radius = {159.0, 145, NULL, "59^{4+}_{4}", "72^{4+}_{6}"},
    reduction_potential = {-1.553, 4, _EOH},
    electronegativity = 1.2,
    mass_fraction = 0.02,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {95, "\beta^{-} \gamma", "64\,d"},
    atomic_mass = 91.224,
    number_natural_isotopes = 5,
    mass_number = [90,92,94],
    abundances = [0.515, 0.171, 0.174],
    ionisation_energy = 6.84,
    density = 6.51,
    transition_point = [2128., 4682.],
  }, %}}}
  struct { %{{{
    name = "Niobium",
    number = 41,
    symbol = "Nb",
    oxidation_stages = [5,3],
    electron_configuration = "4d^{4}5s",
    atomic_radius = {142.9, 134, NULL, "64^{5+}_{6}", "72^{3+}_{6}"},
    reduction_potential = {-1.099, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = 2e-3,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {94, "\beta^{-} \gamma", "2\cdot 10^{4}\,a"},
    atomic_mass = 92.906,
    number_natural_isotopes = 1,
    mass_number = 93,
    abundances = 1.0,
    ionisation_energy = 6.88,
    density = 8.58,
    transition_point = [2750., 5017.],
  }, %}}}
  struct { %{{{
    name = "Molybdenum",
    number = 42,
    symbol = "Mo",
    oxidation_stages = [6,5,4,3,2,0],
    electron_configuration = "4d^{5}5s",
    atomic_radius = {136.3, 130, NULL, "59^{6-}_{6}", "61^{6+}_{6}"},
    reduction_potential = {-0.200, 3, _P2N},
    electronegativity = 1.3,
    mass_fraction = 1e-3,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {99, "\beta^{-} \gamma", "66\,h"},
    atomic_mass = 95.96,
    number_natural_isotopes = 7,
    mass_number = [95,96,98],
    abundances = [0.159, 0.167, 0.241],
    ionisation_energy = 7.099,
    density = 10.28,
    transition_point = [2896., 4912.],
  }, %}}}
  struct { %{{{
    name = "Technetium",
    number = 43,
    symbol = "Tc",
    oxidation_stages = 7,
    electron_configuration = "4d^{6}5s",
    atomic_radius = {135.2, 127, NULL, "56^{7+}_{6}"},
    reduction_potential = {0.400, 2, _P2N},
    electronegativity = 1.4,
    mass_fraction = 5e-16,
    classification = TRANSITION_METAL,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {99, "\beta^{-}", "2.1\cdot 10^{5}\,a"},
    atomic_mass = 98.906,
    number_natural_isotopes = NULL,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 7.28,
    density = 11.49,
    transition_point = [2430., 4538.],
  }, %}}}
  struct { %{{{
    name = "Ruthenium",
    number = 44,
    symbol = "Ru",
    oxidation_stages = [8,6,4,3,2,0,-2],
    electron_configuration = "4d^{7}5s",
    atomic_radius = {132.5, 125, NULL, "62^{4+}_{6}", "68^{3+}_{6}"},
    reduction_potential = {0.455, 2, _P2N},
    electronegativity = 1.4,
    mass_fraction = 2e-6,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {103, "\beta^{-} \gamma", "39\,d"},
    atomic_mass = 101.07,
    number_natural_isotopes = 7,
    mass_number = [101, 102, 104],
    abundances = [0.17, 0.316, 0.187],
    ionisation_energy = 7.37,
    density = 12.45,
    transition_point = [2607., 4423.],
  }, %}}}
  struct { %{{{
    name = "Rhodium",
    number = 45,
    symbol = "Rh",
    oxidation_stages = [5,4,3,1,2,0],
    electron_configuration = "4d^{8}5s",
    atomic_radius = {134.5, 125, NULL, "55^{5+}_{6}", "67^{3+}_{6}"},
    reduction_potential = {0.758, 3, _P2N},
    electronegativity = 1.5,
    mass_fraction = 1e-7,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {105, "\beta^{-} \gamma", "36\,h"},
    atomic_mass = 102.906,
    number_natural_isotopes = 1,
    mass_number = 103,
    abundances = 1.0,
    ionisation_energy = 7.46,
    density = 12.41,
    transition_point = [2237., 3968.],
  }, %}}}
  struct { %{{{
    name = "Palladium",
    number = 46,
    symbol = "Pd",
    oxidation_stages = [4,2,0],
    electron_configuration = "4d^{10}",
    atomic_radius = {137.6, 128, NULL, "64^{2+}_{4}", "86^{2+}_{6}"},
    reduction_potential = {0.951, 2, _P2N},
    electronegativity = 1.4,
    mass_fraction = 1e-6,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {103, "\epsilon", "17\,d"},
    atomic_mass = 106.42,
    number_natural_isotopes = 6,
    mass_number = [105,106,108],
    abundances = [0.223, 0.273, 0.265],
    ionisation_energy = 8.34,
    density = 12.02,
    transition_point = [1828.05, 3236.],
  }, %}}}
  struct { %{{{
    name = "Silver",
    number = 47,
    symbol = "Ag",
    oxidation_stages = [2,1],
    electron_configuration = "4d^{10}5s",
    atomic_radius = {144.5, 134, NULL, "79^{2+}_{4}", "67^{+}_{2}"},
    reduction_potential = {0.800, 1, _P2N},
    electronegativity = 1.4,
    mass_fraction = 1e-5,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {110, "\beta^{-} \gamma", "250\,d"},
    atomic_mass = 107.868,
    number_natural_isotopes = 2,
    mass_number = [107,109],
    abundances = [0.518, 0.482],
    ionisation_energy = 7.576,
    density = 10.49,
    transition_point = [1234.93, 2435.],
  }, %}}}
  struct { %{{{
    name = "Cadmium",
    number = 48,
    symbol = "Cd",
    oxidation_stages = 2,
    electron_configuration = "4d^{10}5s^{2}",
    atomic_radius = {148.9, 141, NULL, "78^{2+}_{4}", "95^{2+}_{6}"},
    reduction_potential = {-0.403, 2, _P2N},
    electronegativity = 1.5,
    mass_fraction = 3e-5,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {109, "\epsilon", "453\,d"},
    atomic_mass = 112.411,
    number_natural_isotopes = 8,
    mass_number = [111,112,114],
    abundances = [0.128,0.241,0.287],
    ionisation_energy = 8.993,
    density = 8.64,
    transition_point = [594.22, 1040.],
  }, %}}}
  struct { %{{{
    name = "Indium",
    number = 49,
    symbol = "In",
    oxidation_stages = 3,
    electron_configuration = "4d^{10}5s^{2}5p",
    atomic_radius = {126.6, 150, NULL, "62^{3+}_{4}", "80^{3+}_{6}"},
    reduction_potential = {-0.338, 3, _P2N},
    electronegativity = 1.5,
    mass_fraction = 1e-5,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {114, "\beta^{-} \gamma", "50\,d"},
    atomic_mass = 114.818,
    number_natural_isotopes = 2,
    mass_number = [113,-115],
    abundances = [0.043, 0.957],
    ionisation_energy = 5.786,
    density = 7.31,
    transition_point = [429.7485, 2345.],
  }, %}}}
  struct { %{{{
    name = "Tin",
    number = 50,
    symbol = "Sn",
    oxidation_stages = [4,2],
    electron_configuration = "4d^{10}5s^{2}5p^{2}",
    atomic_radius = {140.5, 140, NULL, "55^{4-}_{4}", "69^{4+}_{6}"},
    reduction_potential = {-0.138, 2, _P2N},
    electronegativity = 1.7,
    mass_fraction = 3e-3,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {113, "\epsilon \gamma", "115\,d"},
    atomic_mass = 118.71,
    number_natural_isotopes = 10,
    mass_number = [116,118,120],
    abundances = [0.145, 0.242, 0.326],
    ionisation_energy = 7.344,
    density = 7.29,
    transition_point = [505.08, 2875.],
  }, %}}}
  struct { %{{{
    name = "Antimony",
    number = 51,
    symbol = "Sb",
    oxidation_stages = [5,3,-3],
    electron_configuration = "4d^{10}5s^{2}5p^{3}",
    atomic_radius = {145, 141, NULL, "60^{5+}_{6}", "76^{3+}_{6}"},
    reduction_potential = {0.152, 3, _P2N},
    electronegativity = 1.8,
    mass_fraction = 7e-5,
    classification = METALLOID,
    state = SOLID,
    radio_active = STABLE,
    isotope = {125, "\beta^{-} \gamma", "2.8\,a"},
    atomic_mass = 121.76,
    number_natural_isotopes = 2,
    mass_number = [121,123],
    abundances = [0.572, 0.428],
    ionisation_energy = 8.641,
    density = 6.69,
    transition_point = [903.78, 1860.],
  }, %}}}
  struct { %{{{
    name = "Tellurium",
    number = 52,
    symbol = "Te",
    oxidation_stages = [6,4,-2],
    electron_configuration = "4d^{10}5s^{2}5p^{4}",
    atomic_radius = {143.2, 137, NULL, "97^{6+}_{6}", "221^{2-}_{6}"},
    reduction_potential = {-1.143, 2, _N2N},
    electronegativity = 2.0,
    mass_fraction = 1e-6,
    classification = METALLOID,
    state = SOLID,
    radio_active = STABLE,
    isotope = {127, "\beta^{-} \gamma", "109\,d"},
    atomic_mass = 127.6,
    number_natural_isotopes = 8,
    mass_number = [126,-128,-130],
    abundances = [0.19,0.317,0.338],
    ionisation_energy = 9.009,
    density = 6.25,
    transition_point = [722.66, 1261.],
  }, %}}}
  struct { %{{{
    name = "Iodine",
    number = 53,
    symbol = "I",
    oxidation_stages = [7,5,1,-1],
    electron_configuration = "4d^{10}5s^{2}5p^{5}",
    atomic_radius = {133.1, 133, 220, "220^{-}_{6}"},
    reduction_potential = {0.536, 1, _N2N},
    electronegativity = 2.2,
    mass_fraction = 6e-6,
    classification = HALOGEN,
    state = SOLID,
    radio_active = STABLE,
    isotope = {129, "\beta^{-} \gamma", "1.6\cdot 10^{7}\,a"},
    atomic_mass = 126.905,
    number_natural_isotopes = 1,
    mass_number = 127,
    abundances = 1.0,
    ionisation_energy = 10.451,
    density = 4.94,
    transition_point = [386.85, 457.4],
  }, %}}}
  struct { %{{{
    name = "Xenon",
    number = 54,
    symbol = "Xe",
    oxidation_stages = [2,4,6,8],
    electron_configuration = "4d^{10}5s^{2}5p^{6}",
    atomic_radius = {NULL, NULL, 210},
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = 2e-9,
    classification = NOBLE_GAS,
    state = GAS,
    radio_active = STABLE,
    isotope = {133, "\beta^{-} \gamma", "5\,d"},
    atomic_mass = 131.293,
    number_natural_isotopes = 9,
    mass_number = [129,131,132],
    abundances = [0.264, 0.212, 0.269],
    ionisation_energy = 12.13,
    density = -5.89,
    transition_point = [161.4, 165.03],
  }, %}}}
  struct { %{{{
    name = "Caesium",
    number = 55,
    symbol = "Cs",
    oxidation_stages = 1,
    electron_configuration = "6s",
    atomic_radius = {265.5, 253, NULL, "167^{+}_{6}", "174^{+}_{8}"},
    reduction_potential = {-2.92, 1, _P2N},
    electronegativity = 0.9,
    mass_fraction = 6e-4,
    classification = ALKALI_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {137, "\beta^{-} \gamma", "30.2\,a"},
    atomic_mass = 132.906,
    number_natural_isotopes = 1,
    mass_number = 133,
    abundances = 1.0,
    ionisation_energy = 3.894,
    density = 1.9,
    transition_point = [301.59, 944.],
  }, %}}}
  struct { %{{{
    name = "Barium",
    number = 56,
    symbol = "Ba",
    oxidation_stages = 2,
    electron_configuration = "6s^{2}",
    atomic_radius = {217.4, 198, NULL, "135^{2+}_{6}", "142^{2+}_{8}"},
    reduction_potential = {-2.912, 2, _P2N},
    electronegativity = 1.0,
    mass_fraction = 0.03,
    classification = ALKALINE_EARTH_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {133, "\epsilon \gamma", "10.5\,a"},
    atomic_mass = 137.327,
    number_natural_isotopes = 7,
    mass_number = [136,137,138],
    abundances = [0.079, 0.112, 0.717],
    ionisation_energy = 5.212,
    density = 3.65,
    transition_point = [1000., 2170.],
  }, %}}}
  struct { %{{{
    name = "Lanthanum",
    number = 57,
    symbol = "La",
    oxidation_stages = 3,
    electron_configuration = "5d6s^{2}",
    atomic_radius = {187.0, 169, NULL, "103^{3+}_{6}", "116^{3+}_{8}"},
    reduction_potential = {-2.522, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 2e-3,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {140, "\beta^{-} \gamma", "40\,h"},
    atomic_mass = 138.906,
    number_natural_isotopes = 2,
    mass_number = [-138,139],
    abundances = [0.001,0.999],
    ionisation_energy = 5.577,
    density = 6.16,
    transition_point = [1193., 3737.],
  }, %}}}
  struct { %{{{
    name = "Cerium",
    number = 58,
    symbol = "Ce",
    oxidation_stages = [4,3],
    electron_configuration = "4f^{2}6s^{2}",
    atomic_radius = {182.5, 165, NULL, "87^{4+}_{6}", "101^{3+}_{6}"},
    reduction_potential = {-2.483, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 4e-3,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {141, "\beta^{-} \gamma", "33\,d"},
    atomic_mass = 140.116,
    number_natural_isotopes = 4,
    mass_number = [138,140,142],
    abundances = [0.003,0.884,0.111],
    ionisation_energy = 5.47,
    density = 6.77,
    transition_point = [1068., 3716.],
  }, %}}}
  struct { %{{{
    name = "Praseodymium",
    number = 59,
    symbol = "Pr",
    oxidation_stages = [4,3],
    electron_configuration = "4f^{3}6s^{2}",
    atomic_radius = {182.0, 165, NULL, "85^{4+}_{6}", "99^{3+}_{6}"},
    reduction_potential = {-2.35, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 5e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {143, "\beta^{-}", "14\,d"},
    atomic_mass = 140.908,
    number_natural_isotopes = 1,
    mass_number = 141,
    abundances = 1.0,
    ionisation_energy = 5.42,
    density = 6.48,
    transition_point = [1208., 3793.],
  }, %}}}
  struct { %{{{
    name = "Neodymium",
    number = 60,
    symbol = "Nd",
    oxidation_stages = 3,
    electron_configuration = "4f^{4}6s^{2}",
    atomic_radius = {181.4, 164, NULL, "98^{3+}_{6}", "116^{3+}_{9}"},
    reduction_potential = {-2.431, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 2e-3,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {147, "\beta^{-} \gamma", "11\,d"},
    atomic_mass = 144.242,
    number_natural_isotopes = 7,
    mass_number = [142,-144,146],
    abundances = [0.271,0.238,0.172],
    ionisation_energy = 5.49,
    density = 7.0,
    transition_point = [1297., 3347.],
  }, %}}}
  struct { %{{{
    name = "Promethium",
    number = 61,
    symbol = "Pm",
    oxidation_stages = 3,
    electron_configuration = "4f^{5}6s^{2}",
    atomic_radius = {163.0, NULL, NULL, "97^{3+}_{6}", "114^{3+}_{9}"},
    reduction_potential = {-2.29, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 1e-19,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {147,"\beta^{-}", "2.6\,a"},
    atomic_mass = 146.915,
    number_natural_isotopes = NULL,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 5.55,
    density = 7.22,
    transition_point = [1315., 3273.],
  }, %}}}
  struct { %{{{
    name = "Samarium",
    number = 62,
    symbol = "Sm",
    oxidation_stages = [3,2],
    electron_configuration = "4f^{6}6s^{2}",
    atomic_radius = {162.0, NULL, NULL, "96^{3+}_{6}", "113^{3+}_{9}", "132^{2+}_{9}"},
    reduction_potential = {-2.30, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 6e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {153, "\beta^{-} \gamma", "47\,h"},
    atomic_mass = 150.36,
    number_natural_isotopes = 7,
    mass_number = [-147,152,154],
    abundances = [0.15, 0.267, 0.227],
    ionisation_energy = 5.63,
    density = 7.54,
    transition_point = [1345., 2067.],
  }, %}}}
  struct { %{{{
    name = "Europium",
    number = 63,
    symbol = "Eu",
    oxidation_stages = [2,3],
    electron_configuration = "4f^{7}6s^{2}",
    atomic_radius = {199.5, 185, NULL, "95^{3+}_{6}", "117^{2+}_{6}"},
    reduction_potential = {-2.407, 3, _P2N},
    electronegativity = 1.0,
    mass_fraction = 1e-5,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {152, "\epsilon \gamma", "13.3\,a"},
    atomic_mass = 151.964,
    number_natural_isotopes = 2,
    mass_number = [151,153],
    abundances = [0.478,0.522],
    ionisation_energy = 5.67,
    density = 5.25,
    transition_point = [1099., 1802.],
  }, %}}}
  struct { %{{{
    name = "Gadolinium",
    number = 64,
    symbol = "Gd",
    oxidation_stages = 3,
    electron_configuration = "4f^{7}5d6s^{2}",
    atomic_radius = {178.7, 161, NULL, "94^{3+}_{6}", "111^{3+}_{9}"},
    reduction_potential = {-2.29, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 6e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {153, "\epsilon \gamma", "242\,d"},
    atomic_mass = 157.25,
    number_natural_isotopes = 7,
    mass_number = [156,158,160],
    abundances = [0.205, 0.248, 0.219],
    ionisation_energy = 6.14,
    density = 7.89,
    transition_point = [1585., 3546.],
  }, %}}}
  struct { %{{{
    name = "Terbium",
    number = 65,
    symbol = "Tb",
    oxidation_stages = [4,3],
    electron_configuration = "4f^{9}6s^{2}",
    atomic_radius = {176.3, 159, NULL, "92^{3+}_{6}", "110^{3+}_{9}"},
    reduction_potential = {-2.30, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 9e-5,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {160, "\beta^{-} \gamma", "72\,d"},
    atomic_mass = 158.925,
    number_natural_isotopes = 1,
    mass_number = 159,
    abundances = 1.0,
    ionisation_energy = 5.85,
    density = 8.25,
    transition_point = [1629., 3503.],
  }, %}}}
  struct { %{{{
    name = "Dysprosium",
    number = 66,
    symbol = "Dy",
    oxidation_stages = 3,
    electron_configuration = "4f^{10}6s^{2}",
    atomic_radius = {175.2, 159, NULL, "91^{3+}_{6}", "108^{3+}_{9}"},
    reduction_potential = {-2.29, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 4e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {165, "\beta^{-} \gamma", "2\,h"},
    atomic_mass = 162.5,
    number_natural_isotopes = 7,
    mass_number = [162,163,164],
    abundances = [0.255, 0.249, 0.282],
    ionisation_energy = 5.93,
    density = 8.56,
    transition_point = [1680., 2840.],
  }, %}}}
  struct { %{{{
    name = "Holmium",
    number = 67,
    symbol = "Ho",
    oxidation_stages = 3,
    electron_configuration = "4f^{11}6s^{2}",
    atomic_radius = {174.3, 158, NULL, "90^{3+}_{6}", "107^{3+}_{9}"},
    reduction_potential = {-2.33, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 1e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {166, "\beta^{-} \gamma", "1200\,a"},
    atomic_mass = 164.93,
    number_natural_isotopes = 1,
    mass_number = 165,
    abundances = 1.0,
    ionisation_energy = 6.02,
    density = 8.78,
    transition_point = [1734., 2993.],
  }, %}}}
  struct { %{{{
    name = "Erbium",
    number = 68,
    symbol = "Er",
    oxidation_stages = 3,
    electron_configuration = "4f^{12}6s^{2}",
    atomic_radius = {173.4, 157, NULL, "89^{3+}_{6}", "106^{3+}_{9}"},
    reduction_potential = {-2.31, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 2e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {169, "\beta^{-}", "9\,d"},
    atomic_mass = 167.259,
    number_natural_isotopes = 6,
    mass_number = [166,167,168],
    abundances = [0.335, 0.229, 0.27],
    ionisation_energy = 6.1,
    density = 9.05,
    transition_point = [1802., 3141.],
  }, %}}}
  struct { %{{{
    name = "Thulium",
    number = 69,
    symbol = "Tm",
    oxidation_stages = [2,3],
    electron_configuration = "4f^{13}6s^{2}",
    atomic_radius = {172.4, 156, NULL, "88^{3+}_{6}", "105^{3+}_{9}"},
    reduction_potential = {-2.31, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 2e-5,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {170, "\beta^{-} \gamma", "129\,d"},
    atomic_mass = 168.934,
    number_natural_isotopes = 1,
    mass_number = 169,
    abundances = 1.0,
    ionisation_energy = 6.18,
    density = 9.32,
    transition_point = [1818., 2223.],
  }, %}}}
  struct { %{{{
    name = "Ytterbium",
    number = 70,
    symbol = "Yb",
    oxidation_stages = [2,3],
    electron_configuration = "4f^{14}6s^{2}",
    atomic_radius = {194.0, 174, NULL, "87^{3+}_{6}", "104^{3+}_{9}"},
    reduction_potential = {-2.22, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 3e-4,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {169, "\epsilon \gamma", "32\,d"},
    atomic_mass = 173.054,
    number_natural_isotopes = 7,
    mass_number = [172,173,174],
    abundances = [0.219, 0.161, 0.318],
    ionisation_energy = 6.254,
    density = 6.97,
    transition_point = [1097., 1469.],
  }, %}}}
  struct { %{{{
    name = "Lutetium",
    number = 71,
    symbol = "Lu",
    oxidation_stages = 3,
    electron_configuration = "4f^{14}5d6s^{2}",
    atomic_radius = {171.8, 156, NULL, "86^{3+}_{6}", "103^{3+}_{9}"},
    reduction_potential = {-2.30, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 7e-5,
    classification = LANTHANIDE,
    state = SOLID,
    radio_active = STABLE,
    isotope = {177, "\beta^{-} \gamma", "7\,d"},
    atomic_mass = 174.967,
    number_natural_isotopes = 2,
    mass_number = [175,-176],
    abundances = [0.974, 0.026],
    ionisation_energy = 5.426,
    density = 9.84,
    transition_point = [1925., 3675.],
  }, %}}}
  struct { %{{{
    name = "Hafnium",
    number = 72,
    symbol = "Hf",
    oxidation_stages = 4,
    electron_configuration = "4f^{14}5d^{2}6s^{2}",
    atomic_radius = {182.0, 165, NULL, "85^{4+}_{6}", "99^{3+}_{6}"},
    reduction_potential = {-1.505, 4, _EOH},
    electronegativity = 1.2,
    mass_fraction = 4e-4,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {181, "\beta^{-} \gamma", "42\,d"},
    atomic_mass = 178.49,
    number_natural_isotopes = 6,
    mass_number = [177,178,180],
    abundances = [0.186,0.273,0.351],
    ionisation_energy = 7.0,
    density = 13.31,
    transition_point = [2506., 4876.],
  }, %}}}
  struct { %{{{
    name = "Tantalum",
    number = 73,
    symbol = "Ta",
    oxidation_stages = 5,
    electron_configuration = "4f^{14}5d^{3}6s^{2}",
    atomic_radius = {143.0, 134, NULL, "64^{5+}_{6}", "74^{5+}_{8}"},
    reduction_potential = {-0.750, 5, _EOH},
    electronegativity = 1.3,
    mass_fraction = 8e-4,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {182, "\beta^{-} \gamma", "114\,d"},
    atomic_mass = 180.948,
    number_natural_isotopes = 2,
    mass_number = [-180,181],
    abundances = [0.0001, 1.0],
    ionisation_energy = 7.89,
    density = 16.68,
    transition_point = [3290., 5731.],
  }, %}}}
  struct { %{{{
    name = "Tungsten",
    number = 74,
    symbol = "W",
    oxidation_stages = [6,5,4,3,2,0],
    electron_configuration = "4f^{14}5d^{4}6s^{2}",
    atomic_radius = {137.0, 130, NULL, "60^{6+}_{6}", "66^{4+}_{6}"},
    reduction_potential = {-0.09, 4, _EOH},
    electronegativity = 1.4,
    mass_fraction = 6e-3,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {185, "\beta^{-}", "75\,d"},
    atomic_mass = 183.84,
    number_natural_isotopes = 5,
    mass_number = [182,184,186],
    abundances = [0.265, 0.306, 0.284],
    ionisation_energy = 7.98,
    density = 19.26,
    transition_point = [3695., 5828.],
  }, %}}}
  struct { %{{{
    name = "Rhenium",
    number = 75,
    symbol = "Re",
    oxidation_stages = [7,6,4,2,-1],
    electron_configuration = "4f^{14}5d^{5}6s^{2}",
    atomic_radius = {137.1, 128, NULL, "53^{7+}_{6}", "63^{4+}_{6}"},
    reduction_potential = {-0.251, 4, _EOH},
    electronegativity = 1.5,
    mass_fraction = 1e-7,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {186, "\beta^{-} \gamma", "91\,h"},
    atomic_mass = 186.207,
    number_natural_isotopes = 2,
    mass_number = [185,-187],
    abundances = [0.374, 0.626],
    ionisation_energy = 7.88,
    density = 21.03,
    transition_point = [3459., 5869.],
  }, %}}}
  struct { %{{{
    name = "Osmium",
    number = 76,
    symbol = "Os",
    oxidation_stages = [8,6,4,3,2,0,-2],
    electron_configuration = "4f^{14}5d^{6}6s^{2}",
    atomic_radius = {133.8, 126, NULL, "39^{8+}_{4}", "63^{4+}_{6}"},
    reduction_potential = {0.85, 8, _EOH},
    electronegativity = 1.5,
    mass_fraction = 1e-6,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {185, "\epsilon \gamma", "94\,d"},
    atomic_mass = 190.23,
    number_natural_isotopes = 7,
    mass_number = [189,190,192],
    abundances = [0.161,0.263,0.408],
    ionisation_energy = 8.7,
    density = 22.61,
    transition_point = [3306., 5285.],
  }, %}}}
  struct { %{{{
    name = "Iridium",
    number = 77,
    symbol = "Ir",
    oxidation_stages = [6,4,3,2,1,0,-1],
    electron_configuration = "4f^{14}5d^{7}6s^{2}",
    atomic_radius = {135.7, 127, NULL, "63^{4+}_{6}", "68^{3+}_{6}"},
    reduction_potential = {1.156, 3, _P2N},
    electronegativity = 1.6,
    mass_fraction = 1e-7,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {192, "\beta^{-} \gamma", "74\,d"},
    atomic_mass = 192.217,
    number_natural_isotopes = 2,
    mass_number = [192,193],
    abundances = [0.373, 0.627],
    ionisation_energy = 9.1,
    density = 22.65,
    transition_point = [2739., 4701.],
  }, %}}}
  struct { %{{{
    name = "Platinum",
    number = 78,
    symbol = "Pt",
    oxidation_stages = [4,2,0],
    electron_configuration = "4f^{14}5d^{9}6s",
    atomic_radius = {137.3, 130, NULL, "63^{4+}_{6}", "60^{2+}_{4}"},
    reduction_potential = {1.118, 2, _P2N},
    electronegativity = 1.4,
    mass_fraction = 5e-7,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {197, "\beta^{-} \gamma", "18\,h"},
    atomic_mass = 195.084,
    number_natural_isotopes = 6,
    mass_number = [194,195,196],
    abundances = [0.33,0.338,0.252],
    ionisation_energy = 9.0,
    density = 21.45,
    transition_point = [2041.4, 4098.],
  }, %}}}
  struct { %{{{
    name = "Gold",
    number = 79,
    symbol = "Au",
    oxidation_stages = [1,3],
    electron_configuration = "4f^{14}5d^{10}6s",
    atomic_radius = {144.2, 134, NULL, "68^{3+}_{4}", "58^{+}_{2}"},
    reduction_potential = {1.498, 3, _P2N},
    electronegativity = 1.4,
    mass_fraction = 5e-7,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {195, "\epsilon \gamma", "183\,d"},
    atomic_mass = 196.967,
    number_natural_isotopes = 1,
    mass_number = 197,
    abundances = 1.0,
    ionisation_energy = 9.225,
    density = 19.32,
    transition_point = [1337.33, 3129.],
  }, %}}}
  struct { %{{{
    name = "Mercury",
    number = 80,
    symbol = "Hg",
    oxidation_stages = [2,1],
    electron_configuration = "4f^{14}5d^{10}6s^{2}",
    atomic_radius = {150.3, 144, NULL, "96^{2+}_{4}", "119^{+}_{4}"},
    reduction_potential = {0.851, 2, _P2N},
    electronegativity = 1.5,
    mass_fraction = 4e-5,
    classification = TRANSITION_METAL,
    state = LIQUID,
    radio_active = STABLE,
    isotope = {203, "\beta^{-} \gamma", "47\,d"},
    atomic_mass = 200.59,
    number_natural_isotopes = 7,
    mass_number = [199,200,202],
    abundances = [0.169,0.231,0.299],
    ionisation_energy = 10.437,
    density = 13.55,
    transition_point = [234.32, 629.88],
  }, %}}}
  struct { %{{{
    name = "Thallium",
    number = 81,
    symbol = "Tl",
    oxidation_stages = [1,3],
    electron_configuration = "4f^{14}5d^{10}6s^{2}6p",
    atomic_radius = {170.0, 155, NULL, "89^{3+}_{6}", "150^{-}_{6}"},
    reduction_potential = {-0.336, 1, _P2N},
    electronegativity = 1.4,
    mass_fraction = 3e-5,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {204, "\beta^{-}", "3.8\,a"},
    atomic_mass = 204.38,
    number_natural_isotopes = 2,
    mass_number = [203,205],
    abundances = [0.295,0.705],
    ionisation_energy = 6.108,
    density = 11.85,
    transition_point = [577., 1746.],
  }, %}}}
  struct { %{{{
    name = "Lead",
    number = 82,
    symbol = "Pb",
    oxidation_stages = [4,2],
    electron_configuration = "4f^{14}5d^{10}6s^{2}6p^{2}",
    atomic_radius = {175.0, 154, NULL, "78^{4+}_{6}", "119^{2+}_{6}"},
    reduction_potential = {-0.1262, 2, _P2N},
    electronegativity = 1.6,
    mass_fraction = 2e-3,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {210, "\beta^{-} \gamma", "22.3\,a"},
    atomic_mass = 207.2,
    number_natural_isotopes = 4,
    mass_number = [206,207,208],
    abundances = [0.241,0.221,0.524],
    ionisation_energy = 7.416,
    density = 11.34,
    transition_point = [600.61, 2022.],
  }, %}}}
  struct { %{{{
    name = "Bismuth",
    number = 83,
    symbol = "Bi",
    oxidation_stages = [5,3],
    electron_configuration = "4f^{14}5d^{10}6s^{2}6p^{3}",
    atomic_radius = {154.5, 146, NULL, "76^{5+}_{6}", "117^{3+}_{6}"},
    reduction_potential = {0.23, 3, _P2N},
    electronegativity = 1.7,
    mass_fraction = 2e-5,
    classification = POST_TRANSITION_METAL,
    state = SOLID,
    radio_active = STABLE,
    isotope = {207, "\epsilon \gamma", "33.4\,a"},
    atomic_mass = 208.98,
    number_natural_isotopes = 1,
    mass_number = 209,
    abundances = 1.0,
    ionisation_energy = 7.289,
    density = 9.8,
    transition_point = [544.7, 1837.],
  }, %}}}
  struct { %{{{
    name = "Polonium",
    number = 84,
    symbol = "Po",
    oxidation_stages = [6,4,2],
    electron_configuration = "4f^{14}5d^{10}6s^{2}6p^{4}",
    atomic_radius = {167.3, 146, NULL, "67^{6+}_{6}", "94^{4+}_{6}"},
    reduction_potential = NULL,
    electronegativity = 1.8,
    mass_fraction = 2e-14,
    classification = METALLOID,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {209, "\alpha", "130\,a"},
    atomic_mass = 208.982,
    number_natural_isotopes = 7,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 8.42,
    density = 9.20,
    transition_point = [527., 1235.],
  }, %}}}
  struct { %{{{
    name = "Astatine",
    number = 85,
    symbol = "At",
    oxidation_stages = [7,5,3,1,-1],
    electron_configuration = "4f^{14}5d^{10}6s^{2}6p^{5}",
    atomic_radius = {145.0, NULL, NULL, "62^{7+}_{6}"},
    reduction_potential = NULL,
    electronegativity = 2.0,
    mass_fraction = 3e-24,
    classification = HALOGEN,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {210, "\epsilon \gamma", "8.1\,h"},
    atomic_mass = 209.987,
    number_natural_isotopes = 4,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 9.5,
    density = NULL,
    transition_point = [575., 610.],
  }, %}}}
  struct { %{{{
    name = "Radon",
    number = 86,
    symbol = "Rn",
    oxidation_stages = 2,
    electron_configuration = "4f^{14}5d^{10}6s^{2}6p^{6}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = 6e-16,
    classification = NOBLE_GAS,
    state = GAS,
    radio_active = UNSTABLE,
    isotope = {222, "\alpha", "3.8\,d"},
    atomic_mass = 222.018,
    number_natural_isotopes = 4,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 10.748,
    density = 9.73,
    transition_point = [202., 211.3],
  }, %}}}
  struct { %{{{
    name = "Francium",
    number = 87,
    symbol = "Fr",
    oxidation_stages = 1,
    electron_configuration = "7s",
    atomic_radius = {NULL, NULL, NULL, "180^{+}_{6}"},
    reduction_potential = NULL,
    electronegativity = 0.9,
    mass_fraction = 1e-21,
    classification = ALKALI_METAL,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {223, "\beta^{-} \gamma", "22\,m"},
    atomic_mass = 223.02,
    number_natural_isotopes = 1,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 4.0,
    density = NULL,
    transition_point = [300.15, 950.15],
  }, %}}}
  struct { %{{{
    name = "Radium",
    number = 88,
    symbol = "Ra",
    oxidation_stages = 2,
    electron_configuration = "7s^{2}",
    atomic_radius = {NULL, NULL, NULL, "148^{2+}_{8}", "170^{2+}_{9}"},
    reduction_potential = {-2.92, 2, _P2N},
    electronegativity = 1.0,
    mass_fraction = 1e-10,
    classification = ALKALINE_EARTH_METAL,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {226, "\alpha \gamma", "1599\,a"},
    atomic_mass = 226.025,
    number_natural_isotopes = 4,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 5.279,
    density = 5.50,
    transition_point = [973., 2010.],
  }, %}}}
  struct { %{{{
    name = "Actinium",
    number = 89,
    symbol = "Ac",
    oxidation_stages = 3,
    electron_configuration = "6d7s^{2}",
    atomic_radius = {187.8, NULL, NULL, "112^{3+}_{6}"},
    reduction_potential = {-2.13, 3, _P2N},
    electronegativity = 1.0,
    mass_fraction = 6e-14,
    classification = ACTINIDE,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {227, "\beta^{-}", "21.8\,a"},
    atomic_mass = 227.028,
    number_natural_isotopes = 2,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 5.381,
    density = 10.07,
    transition_point = [1323., 3471.],
  }, %}}}
  struct { %{{{
    name = "Thorium",
    number = 90,
    symbol = "Th",
    oxidation_stages = 4,
    electron_configuration = "6d^{2}7s^{2}",
    atomic_radius = {179.8, 165, NULL, "94^{4+}_{6}", "105^{5+}_{8}"},
    reduction_potential = {-1.90, 4, _P2N},
    electronegativity = 1.1,
    mass_fraction = 1e-3,
    classification = ACTINIDE,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {232, "\alpha", "1.4\cdot 10^{10}\,a"},
    atomic_mass = 232.038,
    number_natural_isotopes = 2,
    mass_number = [-230,-232],
    abundances = [5e-6, 1.0],
    ionisation_energy = 6.307,
    density = 11.72,
    transition_point = [2115., 5061.],
  }, %}}}
  struct { %{{{
    name = "Protactinium",
    number = 91,
    symbol = "Pa",
    oxidation_stages = [5,4],
    electron_configuration = "5f^{2}6d7s^{2}",
    atomic_radius = {156.1, NULL, NULL, "78^{5+}_{6}"},
    reduction_potential = {-1.49, 3, _P2N},
    electronegativity = 1.1,
    mass_fraction = 9e-11,
    classification = ACTINIDE,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {231, "\alpha \gamma", "3.3\cdot 10^{4}\,a"},
    atomic_mass = 231.036,
    number_natural_isotopes = 2,
    mass_number = [-231,-234],
    abundances = [1.0, 1e-11],
    ionisation_energy = NULL,
    density = 15.37,
    transition_point = [1841., 4300.],
  }, %}}}
  struct { %{{{
    name = "Uranium",
    number = 92,
    symbol = "U",
    oxidation_stages = [6,5,4,3],
    electron_configuration = "5f^{3}6d7s^{2}",
    atomic_radius = {138.5, 142, NULL, "73^{6+}_{6}", "89^{4+}_{6}"},
    reduction_potential = {-1.798, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = 3e-4,
    classification = ACTINIDE,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {238, "\alpha", "4.5\cdot 10^{9}\,a"},
    atomic_mass = 238.029,
    number_natural_isotopes = 3,
    mass_number = [-234,-235,-238],
    abundances = [0.00005, 0.0072, 0.99275],
    ionisation_energy = 6.194,
    density = 18.97,
    transition_point = [1405.3, 4404.],
  }, %}}}
  struct { %{{{
    name = "Neptunium",
    number = 93,
    symbol = "Np",
    oxidation_stages = [6,5,4,3],
    electron_configuration = "5f^{4}6d7s^{2}",
    atomic_radius = {130.0, NULL, NULL, "72^{6+}_{6}", "75^{5+}_{6}", "101^{3+}_{6}"},
    reduction_potential = {-1.856, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = 4e-17,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {237, "\alpha \gamma", "2.1\cdot 10^{6}\,a"},
    atomic_mass = 237.048,
    number_natural_isotopes = NULL,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 6.266,
    density = 20.48,
    transition_point = [910., 4273.],
  }, %}}}
  struct { %{{{
    name = "Plutonium",
    number = 94,
    symbol = "Pu",
    oxidation_stages = [6,5,4,3],
    electron_configuration = "5f^{6}7s^{2}",
    atomic_radius = {151.3, NULL, NULL, "72^{6+}_{6}", "86^{4+}_{6}", "100^{3+}_{6}"},
    reduction_potential = {-2.031, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = 2e-19,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {244, "\alpha", "8.1\cdot 10^{7}\,a"},
    atomic_mass = 244.064,
    number_natural_isotopes = NULL,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 6.026,
    density = 19.74,
    transition_point = [912.5, 3505.],
  }, %}}}
  struct { %{{{
    name = "Americium",
    number = 95,
    symbol = "Am",
    oxidation_stages = [6,5,4,3],
    electron_configuration = "5f^{7}7s^{2}",
    atomic_radius = {NULL, NULL, NULL, "85^{4+}_{6}", "98^{3+}_{6}"},
    reduction_potential = {-2.07, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {243, "\alpha \gamma", "7370\,a"},
    atomic_mass = 243.061,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 5.974,
    density = 13.67,
    transition_point = [1449., 2880.],
  }, %}}}
  struct { %{{{
    name = "Curium",
    number = 96,
    symbol = "Cm",
    oxidation_stages = [4,3],
    electron_configuration = "5f^{7}6d7s^{2}",
    atomic_radius = {NULL, NULL, NULL, "85^{4+}_{6}", "97^{3+}_{6}"},
    reduction_potential = {-2.06, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {247, "\alpha \gamma", "1.6\cdot 10^{7}\,a"},
    atomic_mass = 247.07,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 5.991,
    density = 13.51,
    transition_point = [1613., 3383.],
  }, %}}}
  struct { %{{{
    name = "Berkelium",
    number = 97,
    symbol = "Bk",
    oxidation_stages = [4,3],
    electron_configuration = "5f^{9}7s^{2}",
    atomic_radius = {NULL, NULL, NULL, "83^{4+}_{6}", "96^{3+}_{6}"},
    reduction_potential = {-1.97, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {247, "\alpha \gamma", "1400\,a"},
    atomic_mass = 247.07,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 6.198,
    density = 13.25,
    transition_point = [1323., -1.],
  }, %}}}
  struct { %{{{
    name = "Californium",
    number = 98,
    symbol = "Cf",
    oxidation_stages = [4,3],
    electron_configuration = "5f^{10}7s^{2}",
    atomic_radius = {NULL, NULL, NULL, "82^{4+}_{6}", "95^{3+}_{6}"},
    reduction_potential = {-2.01, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {251, "\alpha \gamma", "900\,a"},
    atomic_mass = 251.08,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 6.281,
    density = 15.1,
    transition_point = [1173., -1.],
  }, %}}}
  struct { %{{{
    name = "Einsteinium",
    number = 99,
    symbol = "Es",
    oxidation_stages = 3,
    electron_configuration = "5f^{11}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = {-1.98, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {252, "\alpha \gamma", "472\,d"},
    atomic_mass = 252.083,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = 6.368,
    density = NULL,
    transition_point = [1133., -1.],
  }, %}}}
  struct { %{{{
    name = "Fermium",
    number = 100,
    symbol = "Fm",
    oxidation_stages = 3,
    electron_configuration = "5f^{12}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = {-1.95, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {257, "\alpha \gamma", "101\,d"},
    atomic_mass = 257.095,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = [1800., -1.],
  }, %}}}
  struct { %{{{
    name = "Mendelevium",
    number = 101,
    symbol = "Md",
    oxidation_stages = 3,
    electron_configuration = "5d^{13}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = {-1.66, 3, _P2N},
    electronegativity = 1.2,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {258, "\alpha", "51.5\,d"},
    atomic_mass = 258.098,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = [1100., -1.],
  }, %}}}
  struct { %{{{
    name = "Nobelium",
    number = 102,
    symbol = "No",
    oxidation_stages = [3,2],
    electron_configuration = "5f^{14}7s^{2}",
    atomic_radius = {NULL, NULL, NULL, "110^{2+}_{6}"},
    reduction_potential = {-1.78, 3, _P2N},
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {259, "\alpha \epsilon", "58\,m"},
    atomic_mass = 259.101,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = [1100., -1.],
  }, %}}}
  struct { %{{{
    name = "Lawrencium",
    number = 103,
    symbol = "Lr",
    oxidation_stages = 3,
    electron_configuration = "5f^{14}6d7s^{2}",
    atomic_radius = NULL,
    reduction_potential = {-2.06, 3, _P2N},
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = ACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {262, "\epsilon", "3.6\,h"},
    atomic_mass = 262.11,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = [1900., -1.],
  }, %}}}
  struct { %{{{
    name = "Rutherfordium",
    number = 104,
    symbol = "Rf",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{2}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {265, "\alpha", "13\,h"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = [2400., 5800.],
  }, %}}}
  struct { %{{{
    name = "Dubnium",
    number = 105,
    symbol = "Db",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{3}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {268, "\alpha", "1.2\,d"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Seaborgium",
    number = 106,
    symbol = "Sg",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{4}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {271, "\alpha", "2\,m"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Bohrium",
    number = 107,
    symbol = "Bh",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{5}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {270, "\alpha", "1\,m"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Hassium",
    number = 108,
    symbol = "Hs",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{6}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {277, "\alpha", "11\,m"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Meitnerium",
    number = 109,
    symbol = "Mt",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{7}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {276, "\alpha", "0.7\,s"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Darmstadtium",
    number = 110,
    symbol = "Ds",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{9}7s",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {281, "\alpha", "11\,s"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Roentgenium",
    number = 111,
    symbol = "Rg",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSACTINIDE,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {280, "\alpha", "3.6\,s"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Copernicium",
    number = 112,
    symbol = "Cn",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = TRANSITION_METAL,
    state = SOLID,
    radio_active = UNSTABLE,
    isotope = {285, "\alpha", "29\,s"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Nihonium",
    number = 113,
    symbol = "Nh",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s^{2}7p",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = UNKNOWN,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {284, "\alpha", "0.5\,s"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Flerovium",
    number = 114,
    symbol = "Fl",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{5}7s^{2}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = UNKNOWN,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {289, "\alpha", "2.6\,s"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Moscovium",
    number = 115,
    symbol = "Mc",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s^{2}7p^{3}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = UNKNOWN,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {288, "\alpha", "90\,ms"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Livermorium",
    number = 116,
    symbol = "Lv",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s^{2}7p^{4}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = UNKNOWN,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {293, "\alpha", "60\,ms"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Tennessine",
    number = 117,
    symbol = "Ts",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s^{2}7p^{5}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = UNKNOWN,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {294, "\alpha", "80\,ms"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
  struct { %{{{
    name = "Oganesson",
    number = 118,
    symbol = "Og",
    oxidation_stages = NULL,
    electron_configuration = "5f^{14}6d^{10}7s^{2}p^{6}",
    atomic_radius = NULL,
    reduction_potential = NULL,
    electronegativity = NULL,
    mass_fraction = NULL,
    classification = UNKNOWN,
    state = SYNTETIC,
    radio_active = UNSTABLE,
    isotope = {294, "\alpha", "0.9\,ms"},
    atomic_mass = NULL,
    number_natural_isotopes = 0,
    mass_number = NULL,
    abundances = NULL,
    ionisation_energy = NULL,
    density = NULL,
    transition_point = NULL,
  }, %}}}
}; %}}}

variable xcell = 21.5;
variable ycell = 25.;

define val2roman (val) {
  if (typeof(val) != Integer_Type) {
    vmessage("Only Int type can be converted");
    return;
  }
  variable ret = "";
  if (val == 0) return "0";
  if (val < 0) {
    ret = "-";
    val = -val;
  }
  variable final = 0;
  variable c = 0;
  variable rnum = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1];
  variable rlit = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"];
  while (final < val) {
    if ((final+rnum[c]) <= val) {
      ret+=rlit[c];
      final+=rnum[c];
    } else {
      c++;
    }
  }
  return ret;
}

private define state_sym (phase, radioac) {
  variable sym = xfig_plot_new(1.25, 1.25);
  sym.world(0,1.25,0,1.25);
  sym.axes(;off);
  variable scol = qualifier("color", "pse_base");
  if (phase == SOLID) {
    sym.add_object(xfig_new_polyline([0,0,1,1],[0,1,1,0]; closed, fillcolor=scol, color=scol, depth=10), 0,0,-0.5,-0.5);
  } else if (phase == LIQUID) {
    sym.add_object(xfig_new_polyline([[0:1:0.05],1,1,0],[0.2*sin([0:1:0.05]*2*PI)+0.6,0.6,1,1]; closed, fillcolor=scol, color=scol, depth=10), 0,0.4,-0.5,-0.5);
    sym.add_object(xfig_new_polyline([[0:1:0.05],1,1,0],[0.2*sin([0:1:0.05]*2*PI)+0.4,0.4,0,0]; closed, fillcolor=scol, color=scol, depth=10), 0,0,-0.5,-0.5);
  } else if (phase == GAS) {
    sym.add_object(xfig_new_polyline([0,0,1,1,0,0.2,0.8,0.8,0.2,0.2],[0,1,1,0,0,0.2,0.2,0.8,0.8,0.2]; closed, fillcolor=scol, color=scol, depth=10), 0,0,-0.5,-0.5);
  }
  if (radioac == UNSTABLE) {
    sym.add_object(xfig_new_polyline([0,0],[0,1]; color=scol, width=10, depth=10), 1.15,0,-0.5,-0.5);
  }
  sym.scale(3);
  return sym;
}

private define info_text (text, size) {
  variable tfield = xfig_plot_new(1,1);
  tfield.world(0,1,0,1);
  tfield.axes(;off);
  variable align = (qualifier_exists("right")) ? 1. : 0.;
  tfield.xylabel(align,0,text,align-0.5,-0.5;; __qualifiers);
  tfield.scale(size);
  return tfield;
}

private define oxidation (vals) {
  if (vals == NULL) { return "---";}
  vals = vals[array_sort(vals; dir=-1)];
  variable i;
  variable ox = "";
  _for i (0, length(vals)-1,1) {
    ox += val2roman(vals[i]);
    if (i<length(vals)-1) {ox += ",";}
  }
  return ox;
}

private define isotopes (is, ab) {
  if (is == NULL) {
    return "---";
  }
  variable i, str="";
  _for i (0,length(is)-1,1) {
    str += sprintf("%d\,(%.3f)"R, is[i], 100*ab[i]);
    if (i < length(is)-1) {
      str+=",";
    }
  }
  return str;
}

private define temperature (points) {
  variable str1 = "-";
  variable str2 = "-";
  if (points != NULL) {
    if (points[0] > 0 and points[0] < 99) str1 = sprintf("%.2f", points[0]);
    else if (points[0] > 0) str1 = sprintf("%.0f", points[0]);
    if (points[1] > 0 and points[1] < 99) str2 = sprintf("%.2f", points[1]);
    else if (points[1] > 0) str2 = sprintf("%.0f", points[1]);
  }
  return sprintf("$\mathbf{%s/%s}$"R, str1, str2);
}

private variable pos_list = { %{{{
  % 1. periode
  [0*xcell,8*ycell], [17*xcell,8*ycell],
  % 2. periode
  [0*xcell,7*ycell], [1*xcell,7*ycell], [12*xcell,7*ycell], [13*xcell,7*ycell], [14*xcell,7*ycell], [15*xcell,7*ycell], [16*xcell,7*ycell], [17*xcell,7*ycell],
  % 3. periode
  [0*xcell,6*ycell], [1*xcell,6*ycell], [12*xcell,6*ycell], [13*xcell,6*ycell], [14*xcell,6*ycell], [15*xcell,6*ycell], [16*xcell,6*ycell], [17*xcell,6*ycell],
  % 4. periode
  [0*xcell,5*ycell], [1*xcell,5*ycell], [2*xcell,5*ycell], [3*xcell,5*ycell], [4*xcell,5*ycell], [5*xcell,5*ycell], [6*xcell,5*ycell], [7*xcell,5*ycell], [8*xcell,5*ycell],
  [9*xcell,5*ycell], [10*xcell,5*ycell], [11*xcell,5*ycell], [12*xcell,5*ycell], [13*xcell,5*ycell], [14*xcell,5*ycell], [15*xcell,5*ycell], [16*xcell,5*ycell], [17*xcell,5*ycell],
  % 5. periode
  [0*xcell,4*ycell], [1*xcell,4*ycell], [2*xcell,4*ycell], [3*xcell,4*ycell], [4*xcell,4*ycell], [5*xcell,4*ycell], [6*xcell,4*ycell], [7*xcell,4*ycell], [8*xcell,4*ycell],
  [9*xcell,4*ycell], [10*xcell,4*ycell], [11*xcell,4*ycell], [12*xcell,4*ycell], [13*xcell,4*ycell], [14*xcell,4*ycell], [15*xcell,4*ycell], [16*xcell,4*ycell], [17*xcell,4*ycell],
  % 6. periode
  [0*xcell,3*ycell], [1*xcell,3*ycell],
  % lanthanides
  [3*xcell,1*ycell], [4*xcell,1*ycell], [5*xcell,1*ycell], [6*xcell,1*ycell], [7*xcell,1*ycell], [8*xcell,1*ycell], [9*xcell,1*ycell], [10*xcell,1*ycell], [11*xcell,1*ycell],
  [12*xcell,1*ycell], [13*xcell,1*ycell], [14*xcell,1*ycell], [15*xcell,1*ycell], [16*xcell,1*ycell], [17*xcell,1*ycell],
  % 6. periode
  [3*xcell,3*ycell], [4*xcell,3*ycell], [5*xcell,3*ycell], [6*xcell,3*ycell], [7*xcell,3*ycell], [8*xcell,3*ycell], [9*xcell,3*ycell],
  [10*xcell,3*ycell], [11*xcell,3*ycell], [12*xcell,3*ycell], [13*xcell,3*ycell], [14*xcell,3*ycell], [15*xcell,3*ycell], [16*xcell,3*ycell], [17*xcell,3*ycell],
  % 7. periode
  [0*xcell,2*ycell], [1*xcell,2*ycell],
  % actinide
  [3*xcell,0*ycell], [4*xcell,0*ycell], [5*xcell,0*ycell], [6*xcell,0*ycell], [7*xcell,0*ycell], [8*xcell,0*ycell], [9*xcell,0*ycell], [10*xcell,0*ycell], [11*xcell,0*ycell],
  [12*xcell,0*ycell], [13*xcell,0*ycell], [14*xcell,0*ycell], [15*xcell,0*ycell], [16*xcell,0*ycell], [17*xcell,0*ycell],
  % 7. periode
  [3*xcell,2*ycell], [4*xcell,2*ycell], [5*xcell,2*ycell], [6*xcell,2*ycell], [7*xcell,2*ycell], [8*xcell,2*ycell], [9*xcell,2*ycell],
  [10*xcell,2*ycell], [11*xcell,2*ycell], [12*xcell,2*ycell], [13*xcell,2*ycell], [14*xcell,2*ycell], [15*xcell,2*ycell], [16*xcell,2*ycell], [17*xcell,2*ycell],
}; %}}}

define add_element(plot, z) {
  variable cell = xfig_plot_new(xcell, ycell);
  cell.world(0,xcell,0,ycell);
  cell.axes(;off);
  cell.add_object(xfig_new_polyline([0,0,xcell,xcell],[0,ycell,ycell,0]; closed, fillcolor=ecols[element[z].classification], color="pse_border", depth=100, width=20), 0,0,-0.5,-0.5);
  cell.add_object(state_sym(element[z].state, element[z].radio_active), 17,1,-0.5,-0.5);
  cell.add_object(info_text(sprintf("%s"R, element[z].symbol), 16; depth=10, color="pse_base"), 3, 5, -0.5,-0.5);
  cell.add_object(info_text(sprintf("$\mathbf{%d}$"R, element[z].number), 5; right, depth=10), 4.5,4.7,0.5,-0.5);
  cell.add_object(info_text(sprintf("%s"R, element[z].name), 4; depth=10, color="pse_base"), 2,2,-0.5,-0.5);
  cell.add_object(info_text(sprintf("$%s$"R, element[z].electron_configuration), 5; right, depth=10, color="pse_base"), 20,18,0.5,-0.5);
  variable amass = (element[z].atomic_mass == NULL) ? "---"R : sprintf("$%.3f$", element[z].atomic_mass);
  cell.add_object(info_text(amass, 5; depth=10, color="pse_base"), 1,22,-0.5,-0.5);

  cell.add_object(info_text(oxidation(element[z].oxidation_stages), 4; depth=10, color="pse_base"), 1,15,-0.5,-0.5);
  variable nni = (element[z].number_natural_isotopes == NULL) ? "---" : sprintf("$\mathbf{%d}$"R, element[z].number_natural_isotopes);
  cell.add_object(info_text(nni, 5; right, depth=10, color="pse_base"), 20,22,0.5,-0.5);

  cell.add_object(info_text(isotopes(element[z].mass_number, element[z].abundances), 2; depth=10, color="pse_base"), 1.5,20.8,-0.5,-0.5);

  cell.add_object(info_text(temperature(element[z].transition_point), 4; depth=10, color="pse_base"), 1,13,-0.5,-0.5);

  variable eneg = (element[z].electronegativity == NULL) ? "---" : sprintf("$\mathbf{%.1f}$"R, element[z].electronegativity);
  cell.add_object(info_text(eneg, 4; depth=10, right, color="pse_base"), 20,10,0.5,-0.5);

  variable ien = (element[z].ionisation_energy == NULL) ? "---" : sprintf("$\mathbf{%.3f}$"R, element[z].ionisation_energy);
  cell.add_object(info_text(ien, 4; depth=10, right, color="pse_base"), 20, 8,0.5,-0.5);
  plot.add_object(cell, pos_list[z][0], pos_list[z][1], -0.5, -0.5);
}

private define period (plot) {
  variable group = [8,7,5,5,5,5,5,5,5,5,5,5,7,7,7,7,7,8]*ycell;
  variable i;
  _for i (0,17,1) {
    plot.add_object(info_text(sprintf("%d", i+1), 8; depth=10, color="pse_info"), (i+0.6)*xcell,group[i]+1.2*ycell,0,0);
  }
  _for i (0,6,1) {
    plot.add_object(info_text(sprintf("%d", i+1), 8; depth=10, color="pse_info"), 0,(8.6-i)*ycell,0,0);
  }
}

private define groups (plot) {
  variable list = ["Alkali Metals", "Alkaline Earth Metals", "Scandium Group", "Titan Group", "Vanadium Group", "Chromium Group", "Manganese Group", "Iron Group", "Cobalt Group", "Nickel Group", "Copper Group",
		   "Zinc Group", "Borium Group", "Carbon Group", "Nitrogen Group", "Chalcogens", "Halogenes", "Noble Gases", "Lanthanides", "Actinides"];
  variable i;
  variable group = [8,7,5,5,5,5,5,5,5,5,5,5,7,7,7,7,7,8]*ycell;
  variable norm = vector(0,0,1);
  _for i (0,19,1) {
    if (i < 18) {
      plot.add_object(info_text(list[i], 8; depth=10, rotate=70, color="pse_info"), (i+0.4)*xcell, group[i]+1.5*ycell,-0.5,-0.5);
    } else {
      plot.add_object(info_text(list[i], 8; depth=10, color="pse_info"), 18.1*xcell, (19.5-i)*ycell,-0.5,-0.5);
    }
  }
}

private define color_code (plot) {
  variable ccode = ["Hydrogen", "Alkali Metal", "Alkaline Earth Metal", "Transition Metal", "Post-Transition Metal", "Metalloid", "Nonmetal", "Halogen", "Noble Gas", "Lanthanide", "Actinide", "Transactinide", "Unknown"];
  variable col = [HYDROGEN, ALKALI_METAL, ALKALINE_EARTH_METAL, TRANSITION_METAL, POST_TRANSITION_METAL, METALLOID, NONMETAL, HALOGEN, NOBLE_GAS, LANTHANIDE, ACTINIDE, TRANSACTINIDE, UNKNOWN];
  variable i;
  variable baseline = 8*ycell;
  _for i (length(ccode)-1,0,-1) {
    plot.add_object(info_text(ccode[i], 10; color=ecols[col[i]]), 9*xcell,baseline+0.15*ycell*(length(ccode)-1-i),-0.5,-0.5);
  }
}

private define legend (plot) {
  variable leg = xfig_plot_new(2*xcell, 2*ycell);
  variable xpos = 0.055*xcell, ypos = 0.03*ycell, xwidth = 1.94*xcell, ywidth = 1.96*ycell;
  leg.world(0,2*xcell,0,2*ycell);
  leg.axes(;off);
  leg.add_object(xfig_new_polyline([0,xwidth,xwidth,0],[0,0,ywidth,ywidth]; closed, color="pse_info", depth=10, width=20), 0,0,-0.5,-0.5);
  leg.add_object(info_text("Symbol", 14; color="pse_info", depth=10), 6, 10,-0.5,-0.5);
  leg.add_object(info_text("Atomic Number", 5; depth=10, color="pse_info"), 4,8.8,-0.5,-0.5);
  leg.add_object(info_text("Name", 8; depth=10, color="pse_info"), 4,4,-0.5,-0.5);
  leg.add_object(state_sym(SOLID, STABLE; color="pse_info"), 26,4,-0.5,-0.5);
  leg.add_object(state_sym(LIQUID, STABLE; color="pse_info"), 30,4,-0.5,-0.5);
  leg.add_object(state_sym(GAS, UNSTABLE; color="pse_info"), 34,4,-0.5,-0.5);
  leg.add_object(info_text("Solid, Liquid, Radio Active Gas", 3; color="pse_info", depth=10), 21,2,-0.5,-0.5);
  leg.add_object(info_text("Atomic Mass", 5; color="pse_info", depth=10), 2,45,-0.5,-0.5);
  leg.add_object(info_text("\# Natural Isotopes"R, 5; color="pse_info", depth=10, right), 40,44.5,0.5,-0.5);
  leg.add_object(info_text("Isotope Mass Number (Abundances)", 4; color="pse_info", depth=10), 2,42.5,-0.5,-0.5);
  leg.add_object(info_text("Electron Configuration", 6; color="pse_info", depth=10, right), 40,35,0.5,-0.5);
  leg.add_object(info_text("Oxidation Stages", 5; color="pse_info", depth=10), 2,28,-0.5,-0.5);
  leg.add_object(info_text("Melting / Boiling Point", 5; color="pse_info", depth=10), 2, 25,-0.5,-0.5);
  leg.add_object(info_text("Electronegativity", 4; color="pse_info", depth=10, right), 40,20,0.5,-0.5);
  leg.add_object(info_text("Ionisation\n\nEnergy", 4; color="pse_info", depth=10, right), 40,15,0.5,-0.5);
  plot.add_object(leg, xpos,ypos,-0.5,-0.5);
}

define add_insert(plot) {
  variable col1 = "pse_lanthanide";
  variable col2 = "pse_actinide";
  variable lanthanides = xfig_plot_new(xcell,3*ycell);
  lanthanides.world(0,xcell,0,3*ycell);
  lanthanides.axes(;off);
  lanthanides.add_object(xfig_new_polyline([0,0,xcell,xcell,0.8*xcell,0.8*xcell],[2*ycell,3*ycell,3*ycell,0,0,2*ycell]; closed, color="pse_border", fillcolor=col1, depth=100, width=20), 0,0,-0.5,-0.5);
  lanthanides.add_object(info_text("Lanthanides", 7; depth=10), 1,2.3*ycell,-0.5,-0.5);
  
  variable actinides = xfig_plot_new(xcell,3*ycell);
  actinides.world(0,xcell,0,3*ycell);
  actinides.axes(;off);
  actinides.add_object(xfig_new_polyline([0,0,xcell,xcell],[0,3*ycell,3*ycell,0]; closed, color="pse_border", fillcolor=col2, depth=101, width=20), 0,0,-0.5,-0.5);
  actinides.add_object(info_text("Actinides", 7; depth=10), 1,2.3*ycell,-0.5,-0.5);

  plot.add_object(lanthanides, 2.025*xcell, 1*ycell, -0.5,-0.5); % why shifted by .025?
  plot.add_object(actinides, 2.025*xcell, 0*ycell, -0.5,-0.5);
}

define slsh_main () { %{{{
  variable gray=0, info=1, title=1;
  variable output = NULL;
  variable default = "pte.pdf";
  variable i;
  _for i (1,__argc-1,1) {
    if (char(__argv[i][0]) == "-") {
      if      (__argv[i] == "-g") gray=1;
      else if (__argv[i] == "-i") info=1;
      else if (__argv[i] == "-t") title=1;
      else if (__argv[i] == "-ng") gray=0;
      else if (__argv[i] == "-ni") info=0;
      else if (__argv[i] == "-nt") title=0;
      else vmessage ("Unkown option '%s' ignored", __argv[i]);
    } else {
      if (output == NULL) output = __argv[i];
    }
  }
  output = (output == NULL) ? default : output;

  prepare(gray);
  
  variable xworld = 19*xcell, yworld=10*ycell;
  variable PLOT = xfig_plot_new(xworld, yworld);
  xfig_plot_set_point_size(PLOT,50);
  PLOT.world(0,xworld,0,yworld);
  PLOT.axes(;off);

  _for i (0,length(element)-1,1) {
    add_element(PLOT, i);
  }
  add_insert(PLOT);
  period(PLOT);
  if (info) {
    groups(PLOT);
  }
  ifnot (gray) {
    color_code(PLOT);
  }
  legend(PLOT);
  PLOT.add_object(info_text("Key", 8; color="pse_info", depth=10, rotate=90), 0, 1.1*ycell,0,0);
  PLOT.add_object(info_text("\\hspace{0.5cm}Periodic Table\n\n\\hspace{1cm} of the\n\nElements", 25; color="pse_info", depth=10), 0.2*xworld,0.85*yworld,-0.5,-0.5);
  PLOT.add_object(xfig_new_polyline([0,0,1.05*xworld,1.05*xworld],[0,1.1*yworld,1.1*yworld,0]; closed, color="pse_base", width=20), -0.025*xworld,-0.025*yworld,-0.5,-0.5);

  PLOT.render(output);
} %}}}